#!/bin/sh

##!/usr/bin/env bash

# luastatus -b dwm -B separator= \
#   ~/.config/dwm/luastatus/module/backlight.lua \
#   ~/.config/dwm/luastatus/module/alsa.lua \
#   ~/.config/dwm/luastatus/module/battery.lua \
#   ~/.config/dwm/luastatus/module/wifi.lua \
#   ~/.config/dwm/luastatus/module/time-date.lua

while true; do
  luastatus -b dwm -B separator= \
    ~/.config/dwm/luastatus/module/backlight.lua \
    ~/.config/dwm/luastatus/module/alsa.lua \
    ~/.config/dwm/luastatus/module/battery.lua \
    ~/.config/dwm/luastatus/module/wifi.lua \
    ~/.config/dwm/luastatus/module/time-date.lua

  if [ $? -ne 129 ]; then # not SIGHUP
    break
  fi
done
