#!/usr/bin/env bash

prompt="dmenu -l 7 "

uptime=$(uptime -p | sed -e 's/up //g')
dwm_pid="$(pidof dwm)"

hibernate=" Hibernate"
shutdown=" Shutdown"
reboot="󰜉 Reboot"
suspend="󰒲 Suspend"
lock=" Lock"
logout="󰗽 Logout"
cancel="󰖭 Cancel"

option="$cancel\n$hibernate\n$shutdown\n$reboot\n$suspend\n$lock\n$logout"

select="$(echo -e "$option" | $prompt -p "Uptime - $uptime")"

case $select in
$hibernate)
  systemctl hibernate
  ;;
$shutdown)
  kill -TERM dwmpid $dwm_pid
  systemctl poweroff
  ;;
$reboot)
  kill -TERM dwmpid $dwm_pid
  systemctl reboot
  ;;
$suspend)
  systemctl suspend
  ;;
$lock)
  betterlockscreen -l
  ;;
$logout)
  kill -TERM dwmpid $dwm_pid
  ;;
esac
