#!/usr/bin/env bash

_rofi() {
  rofi -dmenu -i -theme $HOME/.config/dwm/external_configs/rofi/buku.rasi -no-levenshtein-sort -width 1000 "$@"
}

# display settings
display_type=2
max_str_width=50

# keybindings
switch_view="Alt+Tab"
new_bookmark="Alt+n"
actions="Alt+a"
edit="Alt+e"
delete="Alt+d"

# colors
help_color="#2d7ed8"
